<div class="example-container">
        <div class="roland-garros-babolat">
            <div class="selectors">
                <a data-zoom-id="rg-babolat" href="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg?scale.width=900" data-zoom-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg" data-image="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg?scale.width=350" data-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg?scale.width=700" class="mz-thumb"><img alt="Magic Zoom Plus - Examples" src="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg?scale.width=60" srcset="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg?scale.width=120 2x"></a>
                <a data-zoom-id="rg-babolat" href="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg?scale.width=900" data-zoom-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg" data-image="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg?scale.width=350" data-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg?scale.width=700" class="mz-thumb mz-thumb-selected"><img alt="Magic Zoom Plus - Examples" src="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg?scale.width=60" srcset="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg?scale.width=120 2x"></a>
                <a data-zoom-id="rg-babolat" href="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-junior-kit.jpg?scale.width=900" data-zoom-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-junior-kit.jpg" data-image="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-junior-kit.jpg?scale.width=350" data-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-junior-kit.jpg?scale.width=700" class="mz-thumb"><img alt="Magic Zoom Plus - Examples" src="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-junior-kit.jpg?scale.width=60" srcset="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-junior-kit.jpg?scale.width=120 2x"></a>
                <a data-zoom-id="rg-babolat" href="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-tote-bag.jpg?scale.width=900" data-zoom-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-tote-bag.jpg" data-image="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-tote-bag.jpg?scale.width=350" data-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-tote-bag.jpg?scale.width=700" class="mz-thumb"><img alt="Magic Zoom Plus - Examples" src="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-tote-bag.jpg?scale.width=60" srcset="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-tote-bag.jpg?scale.width=120 2x"></a>
                <a data-zoom-id="rg-babolat" href="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-ball-magnet.jpg?scale.width=900" data-zoom-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-ball-magnet.jpg" data-image="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-ball-magnet.jpg?scale.width=350" data-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-ball-magnet.jpg?scale.width=700" class="mz-thumb"><img alt="Magic Zoom Plus - Examples" src="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-ball-magnet.jpg?scale.width=60" srcset="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-ball-magnet.jpg?scale.width=120 2x"></a>
            </div>
            <div class="babolat-preview">
                <a class="MagicZoom" id="rg-babolat" href="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg?scale.width=900" data-zoom-image-2x="//magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket.jpg" data-mobile-options="zoomPosition:right;zoomWidth:130%; zoomHeight:100%; zoomDistance:40;" data-options="zoomPosition: #rg-babolat-zoom; zoomWidth:470; zoomHeight:410; selectorTrigger: hover; transitionEffect: false;"><figure class="mz-figure mz-hover-zoom mz-ready" style=""><div class="mz-lens" style="top: 0px; transform: translate(-10000px, -10000px); width: 183px; height: 160px;"><img src="https://magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg?scale.width=350" style="position: absolute; top: 0px; left: 0px; width: 350px; height: 350px; transform: translate(-1px, -40px);"></div><div class="mz-loading"></div><div class="mz-hint mz-hint-hidden"><span class="mz-hint-message">Click to expand</span></div><img src="https://magictoolbox.sirv.com/images/magiczoom/roland-garros-babolat-racket-holder.jpg?scale.width=350" style="max-width: 350px; position: relative; top: 0px; left: 0px; max-height: 350px;"></figure></a>
            </div>
        </div>
 </div>